server:
  port: 2000
spring:
  application:
    name: lt-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
zuul:
  prefix: /api #配置路由前缀
  routes:
    ITEM-SERVICE: /item/**
    UPLOAD-SERVICE:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
ribbon:
  ConnectionTimeOut: 1000 #链接超时时长
  ReadTimeOut: 3500 #读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数